version: 2

jobs:
  build:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Build image
          command: ./build.sh
          environment:
            DOCKER_PUSH: true

workflows:
  version: 2
  build_docker_images:
    jobs:
      - build
